theme: jekyll-theme-hacker
show_downloads: "true"
google_analytics: UA-111339084-4
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
