theme: jekyll-theme-hacker
title: ndo script repo [github]
description: ndo scripts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
